---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Configuración del sitio
- type: directory
  path: content/site_settings/metadata
  label: Metadata
  create: none
  match: "*.json"
- type: directory
  path: content/site_settings/theme
  label: Tema
  create: none
  match: "*.json"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
